import 'package:fluent_ui/fluent_ui.dart';
import '../../core/data/faker_service.dart';
import 'report_status_chip.dart';
import 'report_metric_chip.dart';

class ReportsList extends StatelessWidget {
  final List reports;
  final Function(String) onShowComingSoon;

  const ReportsList({
    super.key,
    required this.reports,
    required this.onShowComingSoon,
  });

  @override
  Widget build(BuildContext context) {
    final fakerService = FakerService();

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(
                  'Recent Reports',
                  style: FluentTheme.of(context).typography.subtitle,
                ),
                const Spacer(),
                const Text('Last 30 days'),
              ],
            ),
            const SizedBox(height: 16),
            SizedBox(
              height: 400,
              child: reports.isEmpty
                  ? const _EmptyState()
                  : ListView.builder(
                      shrinkWrap: true,
                      itemCount: reports.length,
                      itemBuilder: (context, index) {
                        final report = reports[index];
                        return Container(
                          decoration: BoxDecoration(
                            border: index < reports.length - 1
                                ? Border(
                                    bottom: BorderSide(color: Colors.grey[30]),
                                  )
                                : null,
                          ),
                          child: ListTile(
                            leading: _getReportIcon(report.type),
                            title: Text(report.title),
                            subtitle: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text('Generated by ${report.generatedBy.name}'),
                                const SizedBox(height: 4),
                                Row(
                                  children: [
                                    ReportStatusChip(status: report.status),
                                    const SizedBox(width: 8),
                                    Icon(
                                      FluentIcons.clock,
                                      size: 12,
                                      color: Colors.grey[100],
                                    ),
                                    const SizedBox(width: 4),
                                    Text(
                                      fakerService.timeAgo(report.createdAt),
                                      style: const TextStyle(fontSize: 12),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            trailing: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                ReportMetricChip(
                                  icon: FluentIcons.checkbox_composite,
                                  value: '${report.metrics['completion']}%',
                                  color: Colors.green,
                                ),
                                const SizedBox(width: 8),
                                IconButton(
                                  icon: const Icon(
                                    FluentIcons.download,
                                    size: 16,
                                  ),
                                  onPressed: () =>
                                      onShowComingSoon('Download Report'),
                                ),
                                IconButton(
                                  icon: const Icon(FluentIcons.more, size: 16),
                                  onPressed: () =>
                                      _showReportActions(context, report),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _getReportIcon(String type) {
    final icons = {
      'financial': FluentIcons.money,
      'performance': FluentIcons.speed_high,
      'audit': FluentIcons.security_group,
      'analytics': FluentIcons.bar_chart4,
      'compliance': FluentIcons.compliance_audit,
    };
    return CircleAvatar(
      backgroundColor: Colors.blue.withValues(alpha: 10),
      child: Icon(
        icons[type] ?? FluentIcons.report_document,
        size: 20,
        color: Colors.blue,
      ),
    );
  }

  void _showReportActions(BuildContext context, dynamic report) {
    showDialog(
      context: context,
      builder: (context) => ContentDialog(
        title: Text('Report Actions - ${report.title}'),
        content: const Text('Select an action for this report'),
        actions: [
          Button(
            child: const Text('View Details'),
            onPressed: () => Navigator.pop(context),
          ),
          Button(
            child: const Text('Export'),
            onPressed: () {
              Navigator.pop(context);
              onShowComingSoon('Export Report');
            },
          ),
          Button(
            child: const Text('Share'),
            onPressed: () => Navigator.pop(context),
          ),
          Button(
            child: const Text('Delete'),
            onPressed: () => Navigator.pop(context),
          ),
        ],
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  const _EmptyState();

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(FluentIcons.report_document, size: 48),
          SizedBox(height: 16),
          Text('No reports found'),
        ],
      ),
    );
  }
}
